import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Observable } from 'rxjs';
import { AuthService } from '../../core/services/auth/auth';

interface Placement {
  id: string;
  created_by: string;
  company_name: string;
  role_title: string;
  job_description: string;
  ctc_lpa: number;
  location: string;
  required_skills: string[];
  eligibility_criteria: string;
  last_date: string;
  status: 'active' | 'closed' | 'on-hold';
  created_at: string;
  updated_at: string;
}

@Component({
  selector: 'app-dashbaord',
  imports: [CommonModule],
  templateUrl: './dashbaord.html',
  styleUrl: './dashbaord.scss',
})
export class Dashbaord implements OnInit {
  user$: Observable<any>;
  isAdmin = false;

  constructor(private authService: AuthService) {
    this.user$ = this.authService.user$;
  }

  ngOnInit(): void {
    this.user$.subscribe((user: any) => {
      this.isAdmin = user?.role === 'admin';
    });
  }
  placements: Placement[] = [
    {
      id: 'P001',
      created_by: 'admin@university.edu',
      company_name: 'Google',
      role_title: 'Software Engineer',
      job_description: 'Develop scalable web applications and services',
      ctc_lpa: 42,
      location: 'Bangalore',
      required_skills: ['Python', 'JavaScript', 'System Design'],
      eligibility_criteria: 'B.Tech CS/IT with 7+ CGPA',
      last_date: '2026-05-15',
      status: 'active',
      created_at: '2026-03-01',
      updated_at: '2026-03-20',
    },
    {
      id: 'P002',
      created_by: 'admin@university.edu',
      company_name: 'Microsoft',
      role_title: 'Software Development Engineer',
      job_description: 'Build and maintain cloud-based solutions',
      ctc_lpa: 38,
      location: 'Hyderabad',
      required_skills: ['C++', 'Azure', 'Cloud Computing'],
      eligibility_criteria: 'B.Tech/M.Tech with 6.5+ CGPA',
      last_date: '2026-05-10',
      status: 'active',
      created_at: '2026-03-02',
      updated_at: '2026-03-19',
    },
    {
      id: 'P003',
      created_by: 'admin@university.edu',
      company_name: 'Amazon',
      role_title: 'Backend Engineer',
      job_description: 'Design and implement distributed systems',
      ctc_lpa: 36,
      location: 'Bangalore',
      required_skills: ['Java', 'AWS', 'Database Design'],
      eligibility_criteria: 'B.Tech CS/IT with 7+ CGPA',
      last_date: '2026-05-20',
      status: 'active',
      created_at: '2026-03-03',
      updated_at: '2026-03-18',
    },
    {
      id: 'P004',
      created_by: 'hr@tcs.com',
      company_name: 'Tata Consultancy Services',
      role_title: 'Associate Software Engineer',
      job_description: 'Develop and test software applications',
      ctc_lpa: 12,
      location: 'Mumbai',
      required_skills: ['Java', 'C', 'Testing'],
      eligibility_criteria: 'B.Tech/B.Sc with 6+ CGPA',
      last_date: '2026-04-30',
      status: 'active',
      created_at: '2026-03-04',
      updated_at: '2026-03-17',
    },
    {
      id: 'P005',
      created_by: 'hr@infosys.com',
      company_name: 'Infosys',
      role_title: 'System Engineer',
      job_description: 'Support and maintain IT infrastructure',
      ctc_lpa: 11,
      location: 'Pune',
      required_skills: ['Linux', 'Networking', 'Troubleshooting'],
      eligibility_criteria: 'B.Tech/B.Sc with 5.5+ CGPA',
      last_date: '2026-04-25',
      status: 'active',
      created_at: '2026-03-05',
      updated_at: '2026-03-16',
    },
    {
      id: 'P006',
      created_by: 'admin@university.edu',
      company_name: 'Meta',
      role_title: 'Software Engineer',
      job_description: 'Build features for billions of users',
      ctc_lpa: 45,
      location: 'Bangalore',
      required_skills: ['React', 'JavaScript', 'System Design'],
      eligibility_criteria: 'B.Tech/M.Tech with 7.5+ CGPA',
      last_date: '2026-05-25',
      status: 'active',
      created_at: '2026-03-06',
      updated_at: '2026-03-15',
    },
    {
      id: 'P007',
      created_by: 'hr@accenture.com',
      company_name: 'Accenture',
      role_title: 'Technology Analyst',
      job_description: 'Develop solutions for enterprise clients',
      ctc_lpa: 13,
      location: 'Chennai',
      required_skills: ['Java', '.NET', 'SQL'],
      eligibility_criteria: 'B.Tech/B.Sc with 6+ CGPA',
      last_date: '2026-04-20',
      status: 'active',
      created_at: '2026-03-07',
      updated_at: '2026-03-14',
    },
    {
      id: 'P008',
      created_by: 'admin@university.edu',
      company_name: 'Apple',
      role_title: 'iOS Developer',
      job_description: 'Develop innovative iOS applications',
      ctc_lpa: 40,
      location: 'Bangalore',
      required_skills: ['Swift', 'Objective-C', 'iOS Development'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-05-30',
      status: 'active',
      created_at: '2026-03-08',
      updated_at: '2026-03-13',
    },
    {
      id: 'P009',
      created_by: 'hr@wipro.com',
      company_name: 'Wipro',
      role_title: 'Software Developer',
      job_description: 'Develop enterprise applications',
      ctc_lpa: 10.5,
      location: 'Bangalore',
      required_skills: ['Java', 'Spring Boot', 'REST APIs'],
      eligibility_criteria: 'B.Tech/B.Sc with 5.5+ CGPA',
      last_date: '2026-04-15',
      status: 'active',
      created_at: '2026-03-09',
      updated_at: '2026-03-12',
    },
    {
      id: 'P010',
      created_by: 'admin@university.edu',
      company_name: 'Netflix',
      role_title: 'Full Stack Engineer',
      job_description: 'Build streaming platforms and services',
      ctc_lpa: 44,
      location: 'Bangalore',
      required_skills: ['JavaScript', 'Node.js', 'React'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-06-05',
      status: 'active',
      created_at: '2026-03-10',
      updated_at: '2026-03-11',
    },
    {
      id: 'P011',
      created_by: 'hr@cognizant.com',
      company_name: 'Cognizant',
      role_title: 'Programmer Trainee',
      job_description: 'Assist in software development projects',
      ctc_lpa: 9.5,
      location: 'Pune',
      required_skills: ['C', 'Java', 'Problem Solving'],
      eligibility_criteria: 'B.Tech/B.Sc with 5+ CGPA',
      last_date: '2026-04-10',
      status: 'active',
      created_at: '2026-03-11',
      updated_at: '2026-03-10',
    },
    {
      id: 'P012',
      created_by: 'admin@university.edu',
      company_name: 'LinkedIn',
      role_title: 'Software Engineer',
      job_description: 'Build professional network features',
      ctc_lpa: 41,
      location: 'Bangalore',
      required_skills: ['Java', 'Scala', 'Distributed Systems'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-06-01',
      status: 'active',
      created_at: '2026-03-12',
      updated_at: '2026-03-09',
    },
    {
      id: 'P013',
      created_by: 'hr@hcl.com',
      company_name: 'HCL Technologies',
      role_title: 'Associate Programmer',
      job_description: 'Write and test application code',
      ctc_lpa: 10,
      location: 'Noida',
      required_skills: ['C++', 'Python', 'Debugging'],
      eligibility_criteria: 'B.Tech/B.Sc with 5.5+ CGPA',
      last_date: '2026-04-05',
      status: 'on-hold',
      created_at: '2026-03-13',
      updated_at: '2026-03-08',
    },
    {
      id: 'P014',
      created_by: 'admin@university.edu',
      company_name: 'Uber',
      role_title: 'Backend Engineer',
      job_description: 'Scale ride-sharing infrastructure',
      ctc_lpa: 39,
      location: 'Bangalore',
      required_skills: ['Python', 'Go', 'Microservices'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-05-28',
      status: 'active',
      created_at: '2026-03-14',
      updated_at: '2026-03-07',
    },
    {
      id: 'P015',
      created_by: 'hr@hexaware.com',
      company_name: 'Hexaware Technologies',
      role_title: 'Software Developer',
      job_description: 'Develop client solutions',
      ctc_lpa: 11.5,
      location: 'Chennai',
      required_skills: ['Java', 'SQL', 'Web Development'],
      eligibility_criteria: 'B.Tech/B.Sc with 6+ CGPA',
      last_date: '2026-04-18',
      status: 'active',
      created_at: '2026-03-15',
      updated_at: '2026-03-06',
    },
    {
      id: 'P016',
      created_by: 'admin@university.edu',
      company_name: 'Stripe',
      role_title: 'Software Engineer',
      job_description: 'Build payment infrastructure',
      ctc_lpa: 43,
      location: 'Bangalore',
      required_skills: ['Python', 'JavaScript', 'APIs'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-06-10',
      status: 'active',
      created_at: '2026-03-16',
      updated_at: '2026-03-05',
    },
    {
      id: 'P017',
      created_by: 'hr@tech-mahindra.com',
      company_name: 'Tech Mahindra',
      role_title: 'Associate Engineer',
      job_description: 'Support technical operations',
      ctc_lpa: 10.25,
      location: 'Hyderabad',
      required_skills: ['Linux', 'Shell Scripting', 'Monitoring'],
      eligibility_criteria: 'B.Tech/B.Sc with 5.5+ CGPA',
      last_date: '2026-04-12',
      status: 'active',
      created_at: '2026-03-17',
      updated_at: '2026-03-04',
    },
    {
      id: 'P018',
      created_by: 'admin@university.edu',
      company_name: 'Spotify',
      role_title: 'Software Engineer',
      job_description: 'Enhance music streaming experience',
      ctc_lpa: 42,
      location: 'Bangalore',
      required_skills: ['Java', 'Scala', 'Data Processing'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-05-22',
      status: 'active',
      created_at: '2026-03-18',
      updated_at: '2026-03-03',
    },
    {
      id: 'P019',
      created_by: 'hr@synechron.com',
      company_name: 'Synechron',
      role_title: 'Software Engineer',
      job_description: 'Build fintech solutions',
      ctc_lpa: 12.5,
      location: 'Mumbai',
      required_skills: ['Java', 'Python', 'Blockchain'],
      eligibility_criteria: 'B.Tech/M.Tech with 6+ CGPA',
      last_date: '2026-04-22',
      status: 'active',
      created_at: '2026-03-19',
      updated_at: '2026-03-02',
    },
    {
      id: 'P020',
      created_by: 'admin@university.edu',
      company_name: 'PayPal',
      role_title: 'Software Engineer',
      job_description: 'Develop payment solutions',
      ctc_lpa: 40,
      location: 'Bangalore',
      required_skills: ['Java', 'JavaScript', 'Security'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-05-18',
      status: 'active',
      created_at: '2026-03-20',
      updated_at: '2026-03-01',
    },
    {
      id: 'P021',
      created_by: 'hr@mindtree.com',
      company_name: 'Mindtree',
      role_title: 'Full Stack Developer',
      job_description: 'Develop web and mobile applications',
      ctc_lpa: 13,
      location: 'Bangalore',
      required_skills: ['React', 'Node.js', 'MongoDB'],
      eligibility_criteria: 'B.Tech/B.Sc with 6+ CGPA',
      last_date: '2026-04-28',
      status: 'active',
      created_at: '2026-02-01',
      updated_at: '2026-02-28',
    },
    {
      id: 'P022',
      created_by: 'admin@university.edu',
      company_name: 'Airbnb',
      role_title: 'Software Engineer',
      job_description: 'Build travel and hospitality platform',
      ctc_lpa: 41,
      location: 'Bangalore',
      required_skills: ['Python', 'JavaScript', 'React'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-06-08',
      status: 'active',
      created_at: '2026-02-02',
      updated_at: '2026-02-27',
    },
    {
      id: 'P023',
      created_by: 'hr@capgemini.com',
      company_name: 'Capgemini',
      role_title: 'Junior Consultant',
      job_description: 'Consult and develop IT solutions',
      ctc_lpa: 11.75,
      location: 'Pune',
      required_skills: ['Java', 'SQL', 'Agile'],
      eligibility_criteria: 'B.Tech/B.Sc with 6+ CGPA',
      last_date: '2026-04-08',
      status: 'active',
      created_at: '2026-02-03',
      updated_at: '2026-02-26',
    },
    {
      id: 'P024',
      created_by: 'admin@university.edu',
      company_name: 'Slack',
      role_title: 'Software Engineer',
      job_description: 'Build workplace collaboration tools',
      ctc_lpa: 39,
      location: 'Bangalore',
      required_skills: ['JavaScript', 'Go', 'APIs'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-05-12',
      status: 'active',
      created_at: '2026-02-04',
      updated_at: '2026-02-25',
    },
    {
      id: 'P025',
      created_by: 'hr@birlasoft.com',
      company_name: 'BIRLASoft',
      role_title: 'Software Engineer',
      job_description: 'Develop enterprise applications',
      ctc_lpa: 10.5,
      location: 'Bangalore',
      required_skills: ['C#', '.NET', 'SQL Server'],
      eligibility_criteria: 'B.Tech/B.Sc with 5.5+ CGPA',
      last_date: '2026-04-02',
      status: 'closed',
      created_at: '2026-02-05',
      updated_at: '2026-02-24',
    },
    {
      id: 'P026',
      created_by: 'admin@university.edu',
      company_name: 'Robinhood',
      role_title: 'Software Engineer',
      job_description: 'Build financial trading platform',
      ctc_lpa: 44,
      location: 'Bangalore',
      required_skills: ['Python', 'JavaScript', 'Trading'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-06-02',
      status: 'active',
      created_at: '2026-02-06',
      updated_at: '2026-02-23',
    },
    {
      id: 'P027',
      created_by: 'hr@persistent.com',
      company_name: 'Persistent Systems',
      role_title: 'Software Developer',
      job_description: 'Develop software solutions',
      ctc_lpa: 12,
      location: 'Pune',
      required_skills: ['Java', 'Spring', 'Hibernate'],
      eligibility_criteria: 'B.Tech/B.Sc with 6+ CGPA',
      last_date: '2026-04-24',
      status: 'active',
      created_at: '2026-02-07',
      updated_at: '2026-02-22',
    },
    {
      id: 'P028',
      created_by: 'admin@university.edu',
      company_name: 'Shopify',
      role_title: 'Full Stack Engineer',
      job_description: 'Build e-commerce platform',
      ctc_lpa: 42,
      location: 'Bangalore',
      required_skills: ['Ruby', 'JavaScript', 'React'],
      eligibility_criteria: 'B.Tech/M.Tech with 7+ CGPA',
      last_date: '2026-05-26',
      status: 'active',
      created_at: '2026-02-08',
      updated_at: '2026-02-21',
    },
    {
      id: 'P029',
      created_by: 'hr@vti.com',
      company_name: 'Valuebound Tech Innovations',
      role_title: 'Associate Developer',
      job_description: 'Develop web applications',
      ctc_lpa: 9.75,
      location: 'Delhi',
      required_skills: ['Python', 'Django', 'React'],
      eligibility_criteria: 'B.Tech/B.Sc with 5.5+ CGPA',
      last_date: '2026-03-30',
      status: 'closed',
      created_at: '2026-02-09',
      updated_at: '2026-02-20',
    },
  ];

  currentPage = 1;
  itemsPerPage = 10;

  get totalPages(): number {
    return Math.ceil(this.placements.length / this.itemsPerPage);
  }

  get paginatedPlacements(): Placement[] {
    const startIndex = (this.currentPage - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    return this.placements.slice(startIndex, endIndex);
  }

  goToPage(page: number): void {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
    }
  }

  goToPreviousPage(): void {
    this.goToPage(this.currentPage - 1);
  }

  goToNextPage(): void {
    this.goToPage(this.currentPage + 1);
  }
}
